# Generated by Django 3.2.5 on 2023-01-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blok_foam_tirche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_foam', models.ImageField(upload_to='')),
                ('price_tirche', models.ImageField(upload_to='')),
                ('price_blok', models.ImageField(upload_to='')),
            ],
        ),
    ]
